image: node:16

pages:
  cache:
    paths:
      - node_modules
  script:
    - npm install
    - npm run build:prod
    - mv ./dist ./public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
